// Shared breed images mapping - only includes breeds that actually exist in the data
export const breedImages: { [key: string]: any } = {
  'akita': require('@/assets/images/breeds/akita.png'),
  'alapaha blue blood bulldog': require('@/assets/images/breeds/alapaha_blue_blood_bulldog.png'),
  'alaskan malamute': require('@/assets/images/breeds/alaskan_malamute.png'),
  'alusky': require('@/assets/images/breeds/alusky.png'),
  'american bulldog': require('@/assets/images/breeds/american_bulldog.png'),
  'american eskimo dog': require('@/assets/images/breeds/american_eskimo_dog.png'),
  'american foxhound': require('@/assets/images/breeds/american_foxhound.png'),
  'american pit bull terrier': require('@/assets/images/breeds/american_pit_bull_terrier.png'),
  'american staffordshire terrier': require('@/assets/images/breeds/american_staffordshire_terrier.png'),
  'anatolian shepherd dog': require('@/assets/images/breeds/anatolian_shepherd_dog.png'),
  'appenzeller sennenhund': require('@/assets/images/breeds/appenzeller_sennenhund.png'),
  'aussiedoodle': require('@/assets/images/breeds/aussiedoodle.png'),
  'australian cattle dog': require('@/assets/images/breeds/australian_cattle_dog.png'),
  'australian shepherd': require('@/assets/images/breeds/australian_shepherd.png'),
  'barbet': require('@/assets/images/breeds/barbet.png'),
  'basenji': require('@/assets/images/breeds/basenji.png'),
  'basset hound': require('@/assets/images/breeds/basset_hound.png'),
  'beagle': require('@/assets/images/breeds/beagle.png'),
  'bearded collie': require('@/assets/images/breeds/bearded_collie.png'),
  'belgian laekenois': require('@/assets/images/breeds/belgian_laekenois.png'),
  'belgian malinois': require('@/assets/images/breeds/belgian_malinois.png'),
  'belgian sheepdog': require('@/assets/images/breeds/belgian_sheepdog.png'),
  'belgian tervuren': require('@/assets/images/breeds/belgian_tervuren.png'),
  'bergamasco sheepdog': require('@/assets/images/breeds/bergamasco_sheepdog.png'),
  'berger picard': require('@/assets/images/breeds/berger_picard.png'),
  'bernedoodle': require('@/assets/images/breeds/bernedoodle.png'),
  'bernese mountain dog': require('@/assets/images/breeds/bernese_mountain_dog.png'),
  'bichon frise': require('@/assets/images/breeds/bichon_frise.png'),
  'black russian terrier': require('@/assets/images/breeds/black_russian_terrier.png'),
  'bluetick coonhound': require('@/assets/images/breeds/bluetick_coonhound.png'),
  'boerboel': require('@/assets/images/breeds/boerboel.png'),
  'bolognese': require('@/assets/images/breeds/bolognese.png'),
  'border collie': require('@/assets/images/breeds/border_collie.png'),
  'boston terrier': require('@/assets/images/breeds/boston_terrier.png'),
  'boxer': require('@/assets/images/breeds/boxer.png'),
  'briard': require('@/assets/images/breeds/briard.png'),
  'brittany': require('@/assets/images/breeds/brittany.png'),
  'bulldog': require('@/assets/images/breeds/bulldog.png'),
  'cairn terrier': require('@/assets/images/breeds/cairn_terrier.png'),
  'cane corso': require('@/assets/images/breeds/cane_corso.png'),
  'carolina dog': require('@/assets/images/breeds/carolina_dog.png'),
  'cavalier king charles spaniel': require('@/assets/images/breeds/cavalier_king_charles_spaniel.png'),
  'cavapoo': require('@/assets/images/breeds/cavapoo.png'),
  'chihuahua': require('@/assets/images/breeds/chihuahua.png'),
  'chinese crested': require('@/assets/images/breeds/chinese_crested.png'),
  'chiweenie': require('@/assets/images/breeds/chiweenie.png'),
  'cirneco dell\'etna': require('@/assets/images/breeds/cirneco_delletna.png'),
  'clumber spaniel': require('@/assets/images/breeds/clumber_spaniel.png'),
  'cockapoo': require('@/assets/images/breeds/cockapoo.png'),
  'cocker spaniel': require('@/assets/images/breeds/cocker_spaniel.png'),
  'collie': require('@/assets/images/breeds/collie.png'),
  'coton de tulear': require('@/assets/images/breeds/coton_de_tulear.png'),
  'dachshund': require('@/assets/images/breeds/dachshund.png'),
  'dandie dinmont terrier': require('@/assets/images/breeds/dandie_dinmont_terrier.png'),
  'doberman pinscher': require('@/assets/images/breeds/doberman_pinscher.png'),
  'dutch shepherd': require('@/assets/images/breeds/dutch_shepherd.png'),
  'english bulldog': require('@/assets/images/breeds/english_bulldog.png'),
  'english coonhound': require('@/assets/images/breeds/english_coonhound.png'),
  'english foxhound': require('@/assets/images/breeds/english_foxhound.png'),
  'english setter': require('@/assets/images/breeds/english_setter.png'),
  'english springer spaniel': require('@/assets/images/breeds/english_springer_spaniel.png'),
  'english toy spaniel': require('@/assets/images/breeds/english_toy_spaniel.png'),
  'entlebucher mountain dog': require('@/assets/images/breeds/entlebucher_mountain_dog.png'),
  'eurasier': require('@/assets/images/breeds/eurasier.png'),
  'field spaniel': require('@/assets/images/breeds/field_spaniel.png'),
  'finnish lapphund': require('@/assets/images/breeds/finnish_lapphund.png'),
  'finnish spitz': require('@/assets/images/breeds/finnish_spitz.png'),
  'french bulldog': require('@/assets/images/breeds/french_bulldog.png'),
  'german pinscher': require('@/assets/images/breeds/german_pinscher.png'),
  'german shepherd': require('@/assets/images/breeds/german_shepherd_dog.png'),
  'german shorthaired pointer': require('@/assets/images/breeds/german_shorthaired_pointer.png'),
  'german wirehaired pointer': require('@/assets/images/breeds/german_wirehaired_pointer.png'),
  'giant schnauzer': require('@/assets/images/breeds/giant_schnauzer.png'),
  'golden retriever': require('@/assets/images/breeds/golden_retriever.png'),
  'goldendoodle': require('@/assets/images/breeds/goldendoodle.png'),
  'great dane': require('@/assets/images/breeds/great_dane.png'),
  'greater swiss mountain dog': require('@/assets/images/breeds/greater_swiss_mountain_dog.png'),
  'greyhound': require('@/assets/images/breeds/greyhound.png'),
  'havanese': require('@/assets/images/breeds/havanese.png'),
  'ibizan hound': require('@/assets/images/breeds/ibizan_hound.png'),
  'icelandic sheepdog': require('@/assets/images/breeds/icelandic_sheepdog.png'),
  'irish setter': require('@/assets/images/breeds/irish_setter.png'),
  'irish terrier': require('@/assets/images/breeds/irish_terrier.png'),
  'irish water spaniel': require('@/assets/images/breeds/irish_water_spaniel.png'),
  'irish wolfhound': require('@/assets/images/breeds/irish_wolfhound.png'),
  'italian greyhound': require('@/assets/images/breeds/italian_greyhound.png'),
  'jack russell terrier': require('@/assets/images/breeds/jack_russell_terrier.png'),
  'japanese chin': require('@/assets/images/breeds/japanese_chin.png'),
  'keeshond': require('@/assets/images/breeds/keeshond.png'),
  'kerry blue terrier': require('@/assets/images/breeds/kerry_blue_terrier.png'),
  'komondor': require('@/assets/images/breeds/komondor.png'),
  'kuvasz': require('@/assets/images/breeds/kuvasz.png'),
  'labradoodle': require('@/assets/images/breeds/labradoodle.png'),
  'labrador retriever': require('@/assets/images/breeds/labrador_retriever.png'),
  'lagotto romagnolo': require('@/assets/images/breeds/lagotto_romagnolo.png'),
  'lakeland terrier': require('@/assets/images/breeds/lakeland_terrier.png'),
  'leonberger': require('@/assets/images/breeds/leonberger.png'),
  'lhasa apso': require('@/assets/images/breeds/lhasa_apso.png'),
  'lowchen': require('@/assets/images/breeds/lowchen.png'),
  'maltese': require('@/assets/images/breeds/maltese.png'),
  'maltipoo': require('@/assets/images/breeds/maltipoo.png'),
  'manchester terrier': require('@/assets/images/breeds/manchester_terrier.png'),
  'mastiff': require('@/assets/images/breeds/mastiff.png'),
  'miniature bull terrier': require('@/assets/images/breeds/miniature_bull_terrier.png'),
  'miniature schnauzer': require('@/assets/images/breeds/miniature_schnauzer.png'),
  'neapolitan mastiff': require('@/assets/images/breeds/neapolitan_mastiff.png'),
  'newfoundland': require('@/assets/images/breeds/newfoundland.png'),
  'norfolk terrier': require('@/assets/images/breeds/norfolk_terrier.png'),
  'norwegian elkhound': require('@/assets/images/breeds/norwegian_elkhound.png'),
  'norwich terrier': require('@/assets/images/breeds/norwich_terrier.png'),
  'old english sheepdog': require('@/assets/images/breeds/old_english_sheepdog.png'),
  'otterhound': require('@/assets/images/breeds/otterhound.png'),
  'papillon': require('@/assets/images/breeds/papillon.png'),
  'pekingese': require('@/assets/images/breeds/pekingese.png'),
  'pembroke welsh corgi': require('@/assets/images/breeds/pembroke_welsh_corgi.png'),
  'petit basset griffon vendeen': require('@/assets/images/breeds/petit_basset_griffon_vendeen.png'),
  'pharaoh hound': require('@/assets/images/breeds/pharaoh_hound.png'),
  'plott hound': require('@/assets/images/breeds/plott.png'),
  'pointer': require('@/assets/images/breeds/pointer.png'),
  'polish lowland sheepdog': require('@/assets/images/breeds/polish_lowland_sheepdog.png'),
  'pomeranian': require('@/assets/images/breeds/pomeranian.png'),
  'poodle': require('@/assets/images/breeds/poodle.png'),
  'puggle': require('@/assets/images/breeds/puggle.png'),
  'puli': require('@/assets/images/breeds/puli.png'),
  'rat terrier': require('@/assets/images/breeds/rat_terrier.png'),
  'redbone coonhound': require('@/assets/images/breeds/redbone_coonhound.png'),
  'rhodesian ridgeback': require('@/assets/images/breeds/rhodesian_ridgeback.png'),
  'rottweiler': require('@/assets/images/breeds/rottweiler.png'),
  'saint bernard': require('@/assets/images/breeds/saint_bernard.png'),
  'samoyed': require('@/assets/images/breeds/samoyed.png'),
  'schnoodle': require('@/assets/images/breeds/schnoodle.png'),
  'scottish terrier': require('@/assets/images/breeds/scottish_terrier.png'),
  'sealyham terrier': require('@/assets/images/breeds/sealyham_terrier.png'),
  'sheepadoodle': require('@/assets/images/breeds/sheepadoodle.png'),
  'shetland sheepdog': require('@/assets/images/breeds/shetland_sheepdog.png'),
  'shiba inu': require('@/assets/images/breeds/shiba_inu.png'),
  'shih tzu': require('@/assets/images/breeds/shih_tzu.png'),
  'shihpoo': require('@/assets/images/breeds/shihpoo.png'),
  'shorkie': require('@/assets/images/breeds/shorkie.png'),
  'silky terrier': require('@/assets/images/breeds/silky_terrier.png'),
  'skye terrier': require('@/assets/images/breeds/skye_terrier.png'),
  'sloughi': require('@/assets/images/breeds/sloughi.png'),
  'smooth fox terrier': require('@/assets/images/breeds/smooth_fox_terrier.png'),
  'soft coated wheaten terrier': require('@/assets/images/breeds/soft_coated_wheaten_terrier.png'),
  'spanish mastiff': require('@/assets/images/breeds/spanish_mastiff.png'),
  'spanish water dog': require('@/assets/images/breeds/spanish_water_dog.png'),
  'spinone italiano': require('@/assets/images/breeds/spinone_italiano.png'),
  'staffordshire bull terrier': require('@/assets/images/breeds/staffordshire_bull_terrier.png'),
  'sussex spaniel': require('@/assets/images/breeds/sussex_spaniel.png'),
  'swedish vallhund': require('@/assets/images/breeds/swedish_vallhund.png'),
  'thai ridgeback': require('@/assets/images/breeds/thai_ridgeback.png'),
  'tibetan mastiff': require('@/assets/images/breeds/tibetan_mastiff.png'),
  'tibetan spaniel': require('@/assets/images/breeds/tibetan_spaniel.png'),
  'tibetan terrier': require('@/assets/images/breeds/tibetan_terrier.png'),
  'toy fox terrier': require('@/assets/images/breeds/toy_fox_terrier.png'),
  'toy manchester terrier': require('@/assets/images/breeds/toy_manchester_terrier.png'),
  'treeing walker coonhound': require('@/assets/images/breeds/treeing_walker_coonhound.png'),
  'vizsla': require('@/assets/images/breeds/vizsla.png'),
  'weimaraner': require('@/assets/images/breeds/weimaraner.png'),
  'west highland white terrier': require('@/assets/images/breeds/west_highland_white_terrier.png'),
  'whippet': require('@/assets/images/breeds/whippet.png'),
  'xoloitzcuintli': require('@/assets/images/breeds/xoloitzcuintli.png'),
  'yorkipoo': require('@/assets/images/breeds/yorkipoo.png'),
  'yorkshire terrier': require('@/assets/images/breeds/yorkshire_terrier.png'),
};

// Function to get breed image with error handling
export const getBreedImage = (imageFilename: string, breedName: string) => {
  if (!breedName) return null;
  
  // Convert breed name to lowercase for case-insensitive lookup
  const breedKey = breedName.toLowerCase();
  const image = breedImages[breedKey];
  
  if (!image) {
    console.log(`Image not found for breed: "${breedName}" (key: "${breedKey}")`);
    return null;
  }
  
  return image;
}; 