// Shared breed images mapping - only includes breeds that actually exist in the data
export const breedImages: { [key: string]: any } = {
  'akita': require('@/assets/images/breeds_resized/akita.png'),
  'alapaha blue blood bulldog': require('@/assets/images/breeds_resized/alapaha_blue_blood_bulldog.png'),
  'alaskan malamute': require('@/assets/images/breeds_resized/alaskan_malamute.png'),
  'alusky': require('@/assets/images/breeds_resized/alusky.png'),
  'american bulldog': require('@/assets/images/breeds_resized/american_bulldog.png'),
  'american eskimo dog': require('@/assets/images/breeds_resized/american_eskimo_dog.png'),
  'american foxhound': require('@/assets/images/breeds_resized/american_foxhound.png'),
  'american pit bull terrier': require('@/assets/images/breeds_resized/american_pit_bull_terrier.png'),
  'american staffordshire terrier': require('@/assets/images/breeds_resized/american_staffordshire_terrier.png'),
  'anatolian shepherd dog': require('@/assets/images/breeds_resized/anatolian_shepherd_dog.png'),
  'appenzeller sennenhund': require('@/assets/images/breeds_resized/appenzeller_sennenhund.png'),
  'aussiedoodle': require('@/assets/images/breeds_resized/aussiedoodle.png'),
  'australian cattle dog': require('@/assets/images/breeds_resized/australian_cattle_dog.png'),
  'australian shepherd': require('@/assets/images/breeds_resized/australian_shepherd.png'),
  'barbet': require('@/assets/images/breeds_resized/barbet.png'),
  'basenji': require('@/assets/images/breeds_resized/basenji.png'),
  'basset hound': require('@/assets/images/breeds_resized/basset_hound.png'),
  'beagle': require('@/assets/images/breeds_resized/beagle.png'),
  'bearded collie': require('@/assets/images/breeds_resized/bearded_collie.png'),
  'belgian laekenois': require('@/assets/images/breeds_resized/belgian_laekenois.png'),
  'belgian malinois': require('@/assets/images/breeds_resized/belgian_malinois.png'),
  'belgian sheepdog': require('@/assets/images/breeds_resized/belgian_sheepdog.png'),
  'belgian tervuren': require('@/assets/images/breeds_resized/belgian_tervuren.png'),
  'bergamasco sheepdog': require('@/assets/images/breeds_resized/bergamasco_sheepdog.png'),
  'berger picard': require('@/assets/images/breeds_resized/berger_picard.png'),
  'bernedoodle': require('@/assets/images/breeds_resized/bernedoodle.png'),
  'bernese mountain dog': require('@/assets/images/breeds_resized/bernese_mountain_dog.png'),
  'bichon frise': require('@/assets/images/breeds_resized/bichon_frise.png'),
  'black russian terrier': require('@/assets/images/breeds_resized/black_russian_terrier.png'),
  'bluetick coonhound': require('@/assets/images/breeds_resized/bluetick_coonhound.png'),
  'boerboel': require('@/assets/images/breeds_resized/boerboel.png'),
  'bolognese': require('@/assets/images/breeds_resized/bolognese.png'),
  'border collie': require('@/assets/images/breeds_resized/border_collie.png'),
  'boston terrier': require('@/assets/images/breeds_resized/boston_terrier.png'),
  'boxer': require('@/assets/images/breeds_resized/boxer.png'),
  'briard': require('@/assets/images/breeds_resized/briard.png'),
  'brittany': require('@/assets/images/breeds_resized/brittany.png'),
  'bulldog': require('@/assets/images/breeds_resized/bulldog.png'),
  'cairn terrier': require('@/assets/images/breeds_resized/cairn_terrier.png'),
  'cane corso': require('@/assets/images/breeds_resized/cane_corso.png'),
  'carolina dog': require('@/assets/images/breeds_resized/carolina_dog.png'),
  'cavalier king charles spaniel': require('@/assets/images/breeds_resized/cavalier_king_charles_spaniel.png'),
  'cavapoo': require('@/assets/images/breeds_resized/cavapoo.png'),
  'chihuahua': require('@/assets/images/breeds_resized/chihuahua.png'),
  'chinese crested': require('@/assets/images/breeds_resized/chinese_crested.png'),
  'chiweenie': require('@/assets/images/breeds_resized/chiweenie.png'),
  'cirneco dell\'etna': require('@/assets/images/breeds_resized/cirneco_delletna.png'),
  'clumber spaniel': require('@/assets/images/breeds_resized/clumber_spaniel.png'),
  'cockapoo': require('@/assets/images/breeds_resized/cockapoo.png'),
  'cocker spaniel': require('@/assets/images/breeds_resized/cocker_spaniel.png'),
  'collie': require('@/assets/images/breeds_resized/collie.png'),
  'coton de tulear': require('@/assets/images/breeds_resized/coton_de_tulear.png'),
  'dachshund': require('@/assets/images/breeds_resized/dachshund.png'),
  'dandie dinmont terrier': require('@/assets/images/breeds_resized/dandie_dinmont_terrier.png'),
  'doberman pinscher': require('@/assets/images/breeds_resized/doberman_pinscher.png'),
  'dutch shepherd': require('@/assets/images/breeds_resized/dutch_shepherd.png'),
  'english bulldog': require('@/assets/images/breeds_resized/english_bulldog.png'),
  'english coonhound': require('@/assets/images/breeds_resized/english_coonhound.png'),
  'english foxhound': require('@/assets/images/breeds_resized/english_foxhound.png'),
  'english setter': require('@/assets/images/breeds_resized/english_setter.png'),
  'english springer spaniel': require('@/assets/images/breeds_resized/english_springer_spaniel.png'),
  'english toy spaniel': require('@/assets/images/breeds_resized/english_toy_spaniel.png'),
  'entlebucher mountain dog': require('@/assets/images/breeds_resized/entlebucher_mountain_dog.png'),
  'eurasier': require('@/assets/images/breeds_resized/eurasier.png'),
  'field spaniel': require('@/assets/images/breeds_resized/field_spaniel.png'),
  'finnish lapphund': require('@/assets/images/breeds_resized/finnish_lapphund.png'),
  'finnish spitz': require('@/assets/images/breeds_resized/finnish_spitz.png'),
  'french bulldog': require('@/assets/images/breeds_resized/french_bulldog.png'),
  'german pinscher': require('@/assets/images/breeds_resized/german_pinscher.png'),
  'german shepherd': require('@/assets/images/breeds_resized/german_shepherd_dog.png'),
  'german shorthaired pointer': require('@/assets/images/breeds_resized/german_shorthaired_pointer.png'),
  'german wirehaired pointer': require('@/assets/images/breeds_resized/german_wirehaired_pointer.png'),
  'giant schnauzer': require('@/assets/images/breeds_resized/giant_schnauzer.png'),
  'golden retriever': require('@/assets/images/breeds_resized/golden_retriever.png'),
  'goldendoodle': require('@/assets/images/breeds_resized/goldendoodle.png'),
  'great dane': require('@/assets/images/breeds_resized/great_dane.png'),
  'greater swiss mountain dog': require('@/assets/images/breeds_resized/greater_swiss_mountain_dog.png'),
  'greyhound': require('@/assets/images/breeds_resized/greyhound.png'),
  'havanese': require('@/assets/images/breeds_resized/havanese.png'),
  'ibizan hound': require('@/assets/images/breeds_resized/ibizan_hound.png'),
  'icelandic sheepdog': require('@/assets/images/breeds_resized/icelandic_sheepdog.png'),
  'irish setter': require('@/assets/images/breeds_resized/irish_setter.png'),
  'irish terrier': require('@/assets/images/breeds_resized/irish_terrier.png'),
  'irish water spaniel': require('@/assets/images/breeds_resized/irish_water_spaniel.png'),
  'irish wolfhound': require('@/assets/images/breeds_resized/irish_wolfhound.png'),
  'italian greyhound': require('@/assets/images/breeds_resized/italian_greyhound.png'),
  'jack russell terrier': require('@/assets/images/breeds_resized/jack_russell_terrier.png'),
  'japanese chin': require('@/assets/images/breeds_resized/japanese_chin.png'),
  'keeshond': require('@/assets/images/breeds_resized/keeshond.png'),
  'kerry blue terrier': require('@/assets/images/breeds_resized/kerry_blue_terrier.png'),
  'komondor': require('@/assets/images/breeds_resized/komondor.png'),
  'kuvasz': require('@/assets/images/breeds_resized/kuvasz.png'),
  'labradoodle': require('@/assets/images/breeds_resized/labradoodle.png'),
  'labrador retriever': require('@/assets/images/breeds_resized/labrador_retriever.png'),
  'lagotto romagnolo': require('@/assets/images/breeds_resized/lagotto_romagnolo.png'),
  'lakeland terrier': require('@/assets/images/breeds_resized/lakeland_terrier.png'),
  'leonberger': require('@/assets/images/breeds_resized/leonberger.png'),
  'lhasa apso': require('@/assets/images/breeds_resized/lhasa_apso.png'),
  'lowchen': require('@/assets/images/breeds_resized/lowchen.png'),
  'maltese': require('@/assets/images/breeds_resized/maltese.png'),
  'maltipoo': require('@/assets/images/breeds_resized/maltipoo.png'),
  'manchester terrier': require('@/assets/images/breeds_resized/manchester_terrier.png'),
  'mastiff': require('@/assets/images/breeds_resized/mastiff.png'),
  'miniature bull terrier': require('@/assets/images/breeds_resized/miniature_bull_terrier.png'),
  'miniature schnauzer': require('@/assets/images/breeds_resized/miniature_schnauzer.png'),
  'neapolitan mastiff': require('@/assets/images/breeds_resized/neapolitan_mastiff.png'),
  'newfoundland': require('@/assets/images/breeds_resized/newfoundland.png'),
  'norfolk terrier': require('@/assets/images/breeds_resized/norfolk_terrier.png'),
  'norwegian elkhound': require('@/assets/images/breeds_resized/norwegian_elkhound.png'),
  'norwich terrier': require('@/assets/images/breeds_resized/norwich_terrier.png'),
  'old english sheepdog': require('@/assets/images/breeds_resized/old_english_sheepdog.png'),
  'otterhound': require('@/assets/images/breeds_resized/otterhound.png'),
  'papillon': require('@/assets/images/breeds_resized/papillon.png'),
  'pekingese': require('@/assets/images/breeds_resized/pekingese.png'),
  'pembroke welsh corgi': require('@/assets/images/breeds_resized/pembroke_welsh_corgi.png'),
  'petit basset griffon vendeen': require('@/assets/images/breeds_resized/petit_basset_griffon_vendeen.png'),
  'pharaoh hound': require('@/assets/images/breeds_resized/pharaoh_hound.png'),
  'plott hound': require('@/assets/images/breeds_resized/plott.png'),
  'pointer': require('@/assets/images/breeds_resized/pointer.png'),
  'polish lowland sheepdog': require('@/assets/images/breeds_resized/polish_lowland_sheepdog.png'),
  'pomeranian': require('@/assets/images/breeds_resized/pomeranian.png'),
  'poodle': require('@/assets/images/breeds_resized/poodle.png'),
  'puggle': require('@/assets/images/breeds_resized/puggle.png'),
  'puli': require('@/assets/images/breeds_resized/puli.png'),
  'rat terrier': require('@/assets/images/breeds_resized/rat_terrier.png'),
  'redbone coonhound': require('@/assets/images/breeds_resized/redbone_coonhound.png'),
  'rhodesian ridgeback': require('@/assets/images/breeds_resized/rhodesian_ridgeback.png'),
  'rottweiler': require('@/assets/images/breeds_resized/rottweiler.png'),
  'saint bernard': require('@/assets/images/breeds_resized/saint_bernard.png'),
  'samoyed': require('@/assets/images/breeds_resized/samoyed.png'),
  'schnoodle': require('@/assets/images/breeds_resized/schnoodle.png'),
  'scottish terrier': require('@/assets/images/breeds_resized/scottish_terrier.png'),
  'sealyham terrier': require('@/assets/images/breeds_resized/sealyham_terrier.png'),
  'sheepadoodle': require('@/assets/images/breeds_resized/sheepadoodle.png'),
  'shetland sheepdog': require('@/assets/images/breeds_resized/shetland_sheepdog.png'),
  'shiba inu': require('@/assets/images/breeds_resized/shiba_inu.png'),
  'shih tzu': require('@/assets/images/breeds_resized/shih_tzu.png'),
  'shihpoo': require('@/assets/images/breeds_resized/shihpoo.png'),
  'shorkie': require('@/assets/images/breeds_resized/shorkie.png'),
  'silky terrier': require('@/assets/images/breeds_resized/silky_terrier.png'),
  'skye terrier': require('@/assets/images/breeds_resized/skye_terrier.png'),
  'sloughi': require('@/assets/images/breeds_resized/sloughi.png'),
  'smooth fox terrier': require('@/assets/images/breeds_resized/smooth_fox_terrier.png'),
  'soft coated wheaten terrier': require('@/assets/images/breeds_resized/soft_coated_wheaten_terrier.png'),
  'spanish mastiff': require('@/assets/images/breeds_resized/spanish_mastiff.png'),
  'spanish water dog': require('@/assets/images/breeds_resized/spanish_water_dog.png'),
  'spinone italiano': require('@/assets/images/breeds_resized/spinone_italiano.png'),
  'staffordshire bull terrier': require('@/assets/images/breeds_resized/staffordshire_bull_terrier.png'),
  'sussex spaniel': require('@/assets/images/breeds_resized/sussex_spaniel.png'),
  'swedish vallhund': require('@/assets/images/breeds_resized/swedish_vallhund.png'),
  'thai ridgeback': require('@/assets/images/breeds_resized/thai_ridgeback.png'),
  'tibetan mastiff': require('@/assets/images/breeds_resized/tibetan_mastiff.png'),
  'tibetan spaniel': require('@/assets/images/breeds_resized/tibetan_spaniel.png'),
  'tibetan terrier': require('@/assets/images/breeds_resized/tibetan_terrier.png'),
  'toy fox terrier': require('@/assets/images/breeds_resized/toy_fox_terrier.png'),
  'toy manchester terrier': require('@/assets/images/breeds_resized/toy_manchester_terrier.png'),
  'treeing walker coonhound': require('@/assets/images/breeds_resized/treeing_walker_coonhound.png'),
  'vizsla': require('@/assets/images/breeds_resized/vizsla.png'),
  'weimaraner': require('@/assets/images/breeds_resized/weimaraner.png'),
  'west highland white terrier': require('@/assets/images/breeds_resized/west_highland_white_terrier.png'),
  'whippet': require('@/assets/images/breeds_resized/whippet.png'),
  'xoloitzcuintli': require('@/assets/images/breeds_resized/xoloitzcuintli.png'),
  'yorkipoo': require('@/assets/images/breeds_resized/yorkipoo.png'),
  'yorkshire terrier': require('@/assets/images/breeds_resized/yorkshire_terrier.png'),
};

// Function to get breed image with error handling
export const getBreedImage = (imageFilename: string, breedName: string) => {
  if (!breedName) return null;
  
  // Convert breed name to lowercase for case-insensitive lookup
  const breedKey = breedName.toLowerCase();
  const image = breedImages[breedKey];
  
  if (!image) {
    console.log(`Image not found for breed: "${breedName}" (key: "${breedKey}")`);
    return null;
  }
  
  return image;
}; 